package com.municipal.rbac;

import java.util.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import org.springframework.transaction.annotation.Transactional;

@RestController @RequestMapping("/api")
class ApiController {
  private final JdbcTemplate db; private final AuthService auth;
  ApiController(JdbcTemplate db,AuthService auth){this.db=db;this.auth=auth;}
  record Login(String account,String password){} record Check(String appCode,String permissionCode,String requestId){} record Ids(List<Long> ids){}
  @PostMapping("/auth/login") Map<String,Object> login(@RequestBody Login x){if(x.account()==null||x.password()==null)throw ApiException.bad("账号和密码不能为空");return auth.login(x.account().trim(),x.password());}
  @PostMapping("/auth/logout") void logout(@RequestHeader(value="Authorization",required=false)String h){auth.logout(h);}
  @GetMapping("/me") Map<String,Object> me(@RequestHeader("Authorization")String h){var u=auth.require(h);long id=(long)u.get("id");return Map.of("user",u,"roles",rows("SELECT r.id,r.code,r.name FROM roles r JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=? ORDER BY r.id",id),"permissionCount",db.queryForObject("SELECT count(DISTINCT p.id) FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id JOIN user_roles ur ON ur.role_id=rp.role_id WHERE ur.user_id=?",Integer.class,id));}
  @GetMapping("/me/permissions") List<Map<String,Object>> myPermissions(@RequestHeader("Authorization")String h,@RequestParam(required=false)String app){long id=(long)auth.require(h).get("id");String sql="SELECT DISTINCT a.code appCode,a.name appName,p.code,p.module_name module,p.feature_name feature,p.action FROM permissions p JOIN applications a ON a.id=p.app_id JOIN role_permissions rp ON rp.permission_id=p.id JOIN user_roles ur ON ur.role_id=rp.role_id JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND p.enabled=1 AND r.enabled=1";return app==null?rows(sql+" ORDER BY a.id,p.id",id):rows(sql+" AND a.code=? ORDER BY p.id",id,app);}
  @PostMapping("/authorize") Map<String,Object> check(@RequestHeader("Authorization")String h,@RequestBody Check x){var u=auth.require(h);long id=(long)u.get("id");boolean ok=x.permissionCode()!=null&&auth.has(id,x.permissionCode());db.update("INSERT INTO authorization_logs(user_id,username,app_code,permission_code,allowed,request_id,reason) VALUES(?,?,?,?,?,?,?)",id,u.get("username"),Objects.toString(x.appCode(),""),Objects.toString(x.permissionCode(),""),ok?1:0,x.requestId(),ok?"角色权限命中":"未获任何角色授权");return Map.of("allowed",ok,"permissionCode",Objects.toString(x.permissionCode(),""),"requestId",Objects.toString(x.requestId(),""));}
  @GetMapping("/dashboard") Map<String,Object> dashboard(@RequestHeader("Authorization")String h){auth.require(h);return Map.of("users",scalar("users"),"departments",scalar("departments"),"applications",scalar("applications"),"permissions",scalar("permissions"),"roles",scalar("roles"),"authLogs",scalar("authorization_logs"));}
  @GetMapping("/users") List<Map<String,Object>> users(@RequestHeader("Authorization")String h,@RequestParam(defaultValue="")String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="30")int size){auth.require(h);size=Math.min(Math.max(size,1),100);String like="%"+q.trim()+"%";return rows("SELECT u.id,u.employee_no employeeNo,u.username,u.name,u.phone,u.company,d.name department,u.position,u.status,group_concat(r.name, '、') roles FROM users u LEFT JOIN departments d ON d.id=u.department_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.name LIKE ? OR u.username LIKE ? OR u.phone LIKE ? GROUP BY u.id ORDER BY u.id LIMIT ? OFFSET ?",like,like,like,size,page*size);}
  @GetMapping("/users/{id}/roles") List<Map<String,Object>> userRoles(@RequestHeader("Authorization")String h,@PathVariable long id){auth.require(h);return rows("SELECT r.id,r.code,r.name,CASE WHEN ur.user_id IS NULL THEN 0 ELSE 1 END assigned FROM roles r LEFT JOIN user_roles ur ON ur.role_id=r.id AND ur.user_id=? ORDER BY r.id",id);}
  @PutMapping("/users/{id}/roles") @Transactional void setUserRoles(@RequestHeader("Authorization")String h,@PathVariable long id,@RequestBody Ids body){var op=auth.require(h);auth.requireAdmin((long)op.get("id"));if(body.ids()==null)throw ApiException.bad("角色列表不能为空");db.update("DELETE FROM user_roles WHERE user_id=?",id);for(Long rid:new LinkedHashSet<>(body.ids()))db.update("INSERT INTO user_roles(user_id,role_id,granted_by) SELECT ?,id,? FROM roles WHERE id=?",id,op.get("id"),rid);db.update("INSERT INTO authorization_changes(operator_id,target_type,target_id,action,detail) VALUES(?,?,?,?,?)",op.get("id"),"USER",id,"SET_ROLES",body.ids().toString());}
  @GetMapping("/roles") List<Map<String,Object>> roles(@RequestHeader("Authorization")String h){auth.require(h);return rows("SELECT r.id,r.code,r.name,r.description,r.enabled,count(DISTINCT ur.user_id) userCount,count(DISTINCT rp.permission_id) permissionCount FROM roles r LEFT JOIN user_roles ur ON ur.role_id=r.id LEFT JOIN role_permissions rp ON rp.role_id=r.id GROUP BY r.id ORDER BY r.id");}
  @GetMapping("/roles/{id}/permissions") List<Map<String,Object>> rolePermissions(@RequestHeader("Authorization")String h,@PathVariable long id,@RequestParam(defaultValue="")String q){auth.require(h);String like="%"+q+"%";return rows("SELECT p.id,a.name appName,p.module_name module,p.feature_name feature,p.action,p.code,CASE WHEN rp.role_id IS NULL THEN 0 ELSE 1 END assigned FROM permissions p JOIN applications a ON a.id=p.app_id LEFT JOIN role_permissions rp ON rp.permission_id=p.id AND rp.role_id=? WHERE p.feature_name LIKE ? OR p.module_name LIKE ? OR a.name LIKE ? ORDER BY a.id,p.id",id,like,like,like);}
  @PutMapping("/roles/{id}/permissions") @Transactional void setRolePermissions(@RequestHeader("Authorization")String h,@PathVariable long id,@RequestBody Ids body){var op=auth.require(h);auth.requireAdmin((long)op.get("id"));if(body.ids()==null)throw ApiException.bad("权限列表不能为空");db.update("DELETE FROM role_permissions WHERE role_id=?",id);for(Long pid:new LinkedHashSet<>(body.ids()))db.update("INSERT INTO role_permissions(role_id,permission_id) SELECT ?,id FROM permissions WHERE id=?",id,pid);db.update("INSERT INTO authorization_changes(operator_id,target_type,target_id,action,detail) VALUES(?,?,?,?,?)",op.get("id"),"ROLE",id,"SET_PERMISSIONS","count="+body.ids().size());}
  @GetMapping("/applications") List<Map<String,Object>> apps(@RequestHeader("Authorization")String h){auth.require(h);return rows("SELECT a.id,a.code,a.name,a.enabled,count(p.id) permissionCount FROM applications a LEFT JOIN permissions p ON p.app_id=a.id GROUP BY a.id ORDER BY a.id");}
  @GetMapping("/authorization-logs") List<Map<String,Object>> logs(@RequestHeader("Authorization")String h,@RequestParam(defaultValue="100")int limit){long uid=(long)auth.require(h).get("id");auth.requireAdmin(uid);return rows("SELECT id,occurred_at occurredAt,username,app_code appCode,permission_code permissionCode,allowed,request_id requestId,reason FROM authorization_logs ORDER BY id DESC LIMIT ?",Math.min(limit,500));}
  private int scalar(String table){return db.queryForObject("SELECT count(*) FROM "+table,Integer.class);}
  private List<Map<String,Object>> rows(String sql,Object...args){return db.query(sql,(rs,n)->{var m=new LinkedHashMap<String,Object>();var md=rs.getMetaData();for(int i=1;i<=md.getColumnCount();i++)m.put(md.getColumnLabel(i),rs.getObject(i));return m;},args);}
}
