package com.municipal.rbac;

import java.nio.file.*; import java.text.Normalizer; import java.util.*;
import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional;

@Component
class DataInitializer implements ApplicationRunner {
  private final JdbcTemplate db; private final Path source; private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder();
  DataInitializer(JdbcTemplate db,@Value("${rbac.source-dir:.}")String source){this.db=db;this.source=Path.of(source);}
  @Override @Transactional public void run(ApplicationArguments args)throws Exception { if(count("users")==0) seed(); }
  private int count(String table){return db.queryForObject("SELECT count(*) FROM "+table,Integer.class);}
  @Transactional void seed() throws Exception {
    seedDepartments(); Map<String,Long> roles=seedRoles(); long admin=insertUser("ADMIN000","admin","系统管理员",null,"总公司",null,"系统管理员",encoder.encode("admin123"));
    db.update("INSERT INTO user_roles(user_id,role_id,granted_by) VALUES(?,?,?)",admin,roles.get("系统管理员"),admin);
    seedEmployees(roles,admin); seedPermissions(roles); System.out.println("RBAC 初始化完成：员工="+count("users")+"，部门="+count("departments")+"，权限="+count("permissions"));
  }
  private void seedDepartments()throws Exception { var rows=ExcelXmlReader.read(source.resolve("市政公司部门信息表.xlsx")); Map<String,Long> ids=new LinkedHashMap<>(); for(int pass=0;pass<3;pass++)for(int i=1;i<rows.size();i++){var r=rows.get(i);String name=get(r,0),parent=get(r,2);if(name.isBlank()||ids.containsKey(name)||(!parent.isBlank()&&!ids.containsKey(parent)))continue;db.update("INSERT INTO departments(name,manager_name,parent_id) VALUES(?,?,?)",name,get(r,1),parent.isBlank()?null:ids.get(parent));ids.put(name,db.queryForObject("SELECT id FROM departments WHERE name=?",Long.class,name));}}
  private Map<String,Long> seedRoles(){Map<String,Long> out=new LinkedHashMap<>();String[] names={"系统管理员","公司领导","部门经理","项目经理","普通员工"};for(String n:names){String c=safe(n);db.update("INSERT INTO roles(code,name,description) VALUES(?,?,?)",c,n,"由功能权限清单初始化");out.put(n,db.queryForObject("SELECT id FROM roles WHERE name=?",Long.class,n));}return out;}
  private void seedEmployees(Map<String,Long> roles,long admin)throws Exception {var rows=ExcelXmlReader.read(source.resolve("市政公司员工信息表.xlsx"));String hash=encoder.encode("123456");for(int i=1;i<rows.size();i++){var r=rows.get(i);String name=get(r,0),no=get(r,1),company=get(r,2),dept=get(r,3),position=get(r,4),phone=get(r,5);Long deptId=findDepartment(company,dept);long uid=insertUser(no,no,name,phone,company,deptId,position,hash);grant(uid,roles.get("普通员工"),admin);if(isLeader(position,dept))grant(uid,roles.get("公司领导"),admin);if(isDepartmentManager(name,dept,company))grant(uid,roles.get("部门经理"),admin);if((dept.contains("项目")&&position.contains("经理")))grant(uid,roles.get("项目经理"),admin);}}
  private void seedPermissions(Map<String,Long> roles)throws Exception {var rows=ExcelXmlReader.read(source.resolve("市政公司应用软件功能权限清单(1).xlsx"));String app="",module="";for(int i=2;i<rows.size();i++){var r=rows.get(i);if(!get(r,0).isBlank())app=get(r,0);if(!get(r,1).isBlank())module=get(r,1);String feature=get(r,2);if(app.isBlank()||feature.isBlank())continue;long appId=ensureApp(app);Set<String> allActions=new LinkedHashSet<>();Map<String,Set<String>> byRole=new LinkedHashMap<>();for(int c=4;c<=8;c++){String role=switch(c){case 4->"系统管理员";case 5->"公司领导";case 6->"部门经理";case 7->"项目经理";default->"普通员工";};Set<String>a=actions(get(r,c));byRole.put(role,a);allActions.addAll(a);}if(byRole.get("系统管理员").contains("全部")){allActions.remove("全部");allActions.addAll(List.of("查看","新增","编辑","删除","审批","导出","配置"));}for(String action:allActions){if(action.equals("全部"))continue;String code=safe(app)+":"+safe(module)+":"+safe(feature)+":"+actionCode(action);db.update("INSERT OR IGNORE INTO permissions(app_id,module_name,feature_name,action,code,description) VALUES(?,?,?,?,?,?)",appId,module,feature,action,code,get(r,3));long pid=db.queryForObject("SELECT id FROM permissions WHERE code=?",Long.class,code);for(var e:byRole.entrySet())if(e.getValue().contains("全部")||e.getValue().contains(action))db.update("INSERT OR IGNORE INTO role_permissions(role_id,permission_id) VALUES(?,?)",roles.get(e.getKey()),pid);}}}
  private long insertUser(String no,String username,String name,String phone,String company,Long dept,String position,String hash){db.update("INSERT INTO users(employee_no,username,name,phone,company,department_id,position,password_hash) VALUES(?,?,?,?,?,?,?,?)",no,username,name,phone,company,dept,position,hash);return db.queryForObject("SELECT id FROM users WHERE username=?",Long.class,username);}
  private void grant(long u,long r,long by){db.update("INSERT OR IGNORE INTO user_roles(user_id,role_id,granted_by) VALUES(?,?,?)",u,r,by);}
  private Long findDepartment(String company,String dept){for(String n:List.of(company+"-"+dept,dept,company))if(n!=null&&!n.isBlank()){var x=db.query("SELECT id FROM departments WHERE name=?",(rs,i)->rs.getLong(1),n);if(!x.isEmpty())return x.get(0);}return null;}
  private boolean isDepartmentManager(String name,String dept,String company){return db.queryForObject("SELECT count(*) FROM departments WHERE manager_name=? AND (name=? OR name=? OR name=?)",Integer.class,name,dept,company+"-"+dept,company)>0;}
  private boolean isLeader(String p,String d){return d.equals("公司领导")||p.matches(".*(董事长|总经理|总工程师|总会计师|党委副书记|工会主席|总经理助理|董事会秘书).*");}
  private long ensureApp(String n){String c=safe(n);db.update("INSERT OR IGNORE INTO applications(code,name) VALUES(?,?)",c,n);return db.queryForObject("SELECT id FROM applications WHERE code=?",Long.class,c);}
  private static Set<String> actions(String s){Set<String>r=new LinkedHashSet<>();if(s==null||s.isBlank()||s.equals("无"))return r;for(String x:s.split("[/、,，]"))if(!x.isBlank())r.add(x.trim());return r;}
  private static String get(List<String>r,int i){return i<r.size()&&r.get(i)!=null?r.get(i).trim():"";}
  private static String safe(String s){String n=Normalizer.normalize(s,Normalizer.Form.NFKC).replaceAll("[^\\p{L}\\p{N}]+","_").replaceAll("^_|_$","");return n.toLowerCase(Locale.ROOT);}
  private static String actionCode(String s){return Map.of("查看","read","新增","create","编辑","update","删除","delete","审批","approve","导出","export","配置","configure").getOrDefault(s,safe(s));}
}
